### ISSUE TITLE
Cannot build the code

### ISSUE THREAD

**Issue by dzenanz** [gabysbrain/tuner#23]
Running `bin/sbt build` from GitBash console on Windows7:

$ bin/sbt build
[info] Loading project definition from C:\PETCT-Phantom\tuner2\project
[info] Updating {file:/C:/PETCT-Phantom/tuner2/project/}tuner2-build...
[info] Resolving net.ceedubs#sbt-ctags;0.1.0 ...
...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to C:\PETCT-Phantom\tuner2\project\target\scala-2.10\sbt-0.13\classes...
[warn] there were 1 deprecation warning(s); re-run with -deprecation for details
[warn] one warning found
[info] Set current project to Tuner (in build file:/C:/PETCT-Phantom/tuner2/)
[error] Not a valid command: build
[error] Not a valid project ID: build
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: build (similar: loaded-build, loadedBuild)
[error] build
[error]      ^

**Comment by dzenanz** [comment]
Running it on Linux (Fedora 21 x64) fails too:

[dzenan@localhost tuner]$ bin/sbt build
Downloading sbt launcher for 0.13.9:
  From  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.9/sbt-launch.jar
    To  /home/dzenan/.sbt/launchers/0.13.9/sbt-launch.jar
Getting org.scala-sbt sbt 0.13.9 ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.9/jars/sbt.jar ...
	[SUCCESSFUL ] org.scala-sbt#sbt;0.13.9!sbt.jar (623ms)
downloading https://jcenter.bintray.com/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.jar ...
	[SUCCESSFUL ] org.scala-lang#scala-library;2.10.5!scala-library.jar (2652ms)

...

[info] 	[SUCCESSFUL ] org.fusesource.scalate#scalate-util_2.10;1.6.1!scalate-util_2.10.jar(bundle) (1091ms)
[info] downloading https://jcenter.bintray.com/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar ...
[info] 	[SUCCESSFUL ] org.slf4j#slf4j-api;1.7.5!slf4j-api.jar (334ms)
[info] Done updating.
[info] Compiling 1 Scala source to /home/dzenan/tuner/project/target/scala-2.10/sbt-0.13/classes...
[warn] there were 1 deprecation warning(s); re-run with -deprecation for details
[warn] one warning found
[info] Set current project to Tuner (in build file:/home/dzenan/tuner/)
[error] Not a valid command: build
[error] Not a valid project ID: build
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: build (similar: loaded-build, loadedBuild)
[error] build
[error]      ^
[dzenan@localhost tuner]$

**Comment by dzenanz** [comment]
For future reference: I was able to start Tuner after importing the project into an IDE:
https://www.jetbrains.com/idea/features/scala.html

**Comment by gabysbrain** [comment]
Oh, oops, The mistake is in the documentation.  It should be `bin/sbt compile`. I fixed the docs.  Thanks!
fda513a5c7bcc5906c853d7174eea24f2ff1af06

**Comment by dzenanz** [comment]
On Fedora 21, it compiles and runs now. On Windows, it is now a different error:

*Dzenan@Xeonator MINGW64 /c/PETCT-Phantom/tuner3 (master)*
`$ bin/sbt compile`
[info] Loading project definition from C:\PETCT-Phantom\tuner3\project
[info] Set current project to Tuner (in build file:/C:/PETCT-Phantom/tuner3/)
[info] Compiling 113 Scala sources and 3 Java sources to C:\PETCT-Phantom\tuner3\target\scala-2.10\classes...
[warn] C:\PETCT-Phantom\tuner3\src\main\scala\tuner\gui\NewProjectWindow.scala:146: This catches all Throwables. If this is really intended, use `case _ : Throwable` to clear this warning.
[warn]           case _ => None
[warn]                ^
[warn] C:\PETCT-Phantom\tuner3\src\main\scala\tuner\ViewInfo.scala:42: match may not be exhaustive.
[warn] It would fail on the following input: Some((x: String forSome x not in ("hyperslice", "splom")))
[warn]     v.currentVis = vi.currentVis match {
[warn]                       ^
[warn] C:\PETCT-Phantom\tuner3\src\main\scala\tuner\gui\widgets\Colorbar.scala:194: match may not be exhaustive.
[warn] It would fail on the following inputs: P2D, PDF
[warn]     applet.renderer match {
[warn]            ^
[warn] there were 4 deprecation warning(s); re-run with -deprecation for details
[warn] there were 68 feature warning(s); re-run with -feature for details
[warn] 5 warnings found
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 28 s, completed Oct 6, 2015 4:12:21 PM

*Dzenan@Xeonator MINGW64 /c/PETCT-Phantom/tuner3 (master)*

**Comment by gabysbrain** [comment]
What version of java and windows are you running? It looks like javac is just quitting without any error message. Tuner compiles fine on my machine with windows and appveyor but maybe something is different on your machine

**Comment by dzenanz** [comment]
I resolved the issue. I needed to manually add JDK bin folder to path. Installing JDK does not do that. Previously I added a symlink to javac.exe in C:\ProgramData\Oracle\Java\javapath (as was done for java, javaw and javaws). That allowed javac to work only partially.

Now I can run tuner in Windows using Git Bash. Thanks for the help Tom, and for the tool!

**Comment by gabysbrain** [comment]
Ok, great! Does this mean that #24 is also resolved?

**Comment by dzenanz** [comment]
No, #23 is still unresolved.
