### ISSUE TITLE
Running samples hangs

### ISSUE THREAD

**Issue by dzenanz** [gabysbrain/tuner#26]
I wrote a sampling script, and when trying to create a new project tuner enters "Running samples (0/10)" step, and then nothing happens. The sampling script is not invoked, and the program just waits.

**Comment by gabysbrain** [comment]
hmm, weird. would it be possible to send me your script privately?

**Comment by dzenanz** [comment]
Here is a [link](https://dl.dropboxusercontent.com/u/48665006/tunerCostFunction.zip) to a zip file with a couple of failed importing attempts and one with sampling script. I have not touched this since October.
